Implementación de ObjetMother
fjmn2001/testing-course pull request #18
Opened 2021-12-22 12:34 UTC by gabrielsalazar8486

2021-12-22 12:59 UTC, gibmyx requested changes
Cambios requeridos y consultas realizadas. @gabrielsalazar8486

2021-12-22 12:59 UTC, gibmyx commented on src/GJ8486/Manga/Infrastructure/MangaPersistenceText.php
> +
los metodos "Update" en el repostorio no retornan nada @gabrielsalazar8486

2021-12-22 12:59 UTC, gibmyx commented on src/GJ8486/Manga/Application/MangaCreate.php
>      }
Despues de crear un recursos. es recomendable no retornar nada a menos que sea estrictamente necesario. @gabrielsalazar8486

2021-12-22 12:59 UTC, gibmyx commented on src/GJ8486/Manga/Application/MangaUpdate.php
> +        return $this->mangaPresistence->update($manga);
igual aqui. @gabrielsalazar8486

2021-12-22 12:59 UTC, gibmyx commented on src/GJ8486/Manga/Application/MangaUpdate.php
> +        $manga = $this->mangaPresistence->findOne($request['id']);
no tiene validacion en caso de que no consiga el recurso que esta buscando? @gabrielsalazar8486

2021-12-22 12:59 UTC, gibmyx commented on src/GJ8486/Manga/Infrastructure/MangaPersistenceText.php
>             : [];
lo ideal no seria no seria devolver la entidad o en caso contratio Null. @gabrielsalazar8486

2021-12-22 12:59 UTC, gibmyx commented on tests/GJ8486/Manga/Application/MangaFindOneTest.php
>          $result = $findOne('20202020200');
porque no trabajas mejor con un Request

2021-12-22 12:59 UTC, gibmyx commented on tests/GJ8486/Manga/Application/MangaUpdateTest.php
> +
igual aqui. porque no trabajas mejor con un Request @gabrielsalazar8486

2021-12-22 16:59 UTC, gabrielsalazar8486 commented on tests/GJ8486/Manga/Application/MangaFindOneTest.php
>          $result = $findOne('20202020200');
Por los momentos no veo necesario utilizar Request, ya que esto es mas que todo para practicar testing.

2021-12-22 16:59 UTC, gabrielsalazar8486 commented on tests/GJ8486/Manga/Application/MangaUpdateTest.php
> +
Por los momentos no veo necesario utilizar Request, ya que esto es mas que todo para practicar testing. @gibmyx

2021-12-22 17:27 UTC, fjmn2001 approved these changes
@gabrielsalazar8486 lo paso pero temas mejorables en los nombres de los metodos y clases siguiendo la arquitectura hexagonal

2021-12-22 17:27 UTC, fjmn2001 commented on src/GJ8486/Manga/Application/MangaCreate.php
>      public function __invoke(array $request)
@gabrielsalazar8486 importante hace explicito en tipo de retorno

2021-12-23 13:43 UTC, dmarcanor reviewed
Cambios solicitados @gabrielsalazar8486

2021-12-23 13:43 UTC, dmarcanor commented on src/GJ8486/Manga/Application/MangaUpdate.php
> +        $manga = $this->mangaPresistence->findOne($request['id']);
El nombre de los casos de uso debe ser en infinitivo @gabrielsalazar8486

2021-12-23 13:43 UTC, dmarcanor commented on src/GJ8486/Manga/Domain/Manga.php
> +    public function autorChange(string $new_value)
Deberían ser AccionPropiedad, es decir, changeAutor @gabrielsalazar8486

2021-12-23 13:43 UTC, dmarcanor commented on tests/GJ8486/Manga/Application/MangaCreateTest.php
>          $repository = new MangaPersistenceText;
Como este es un test unitario deberías mockear el repositorio

2021-12-23 13:43 UTC, dmarcanor commented on tests/GJ8486/Manga/Application/MangaCreateTest.php
> +        $nuevo_manga = [ 'id' => '20202020202', 'nombre' => 'Vinland Saga', 'autor' => 'Makoto Yukimura', 'estado' => 'En emisión'];
Aquí puedes aplicar objectMother de request @gabrielsalazar8486

2021-12-23 19:19 UTC, gabrielsalazar8486 commented on tests/GJ8486/Manga/Application/MangaCreateTest.php
> +        $nuevo_manga = [ 'id' => '20202020202', 'nombre' => 'Vinland Saga', 'autor' => 'Makoto Yukimura', 'estado' => 'En emisión'];
no es estoy implementado request aun @dmarcanor

2021-12-23 19:26 UTC, gabrielsalazar8486 commented on src/GJ8486/Manga/Infrastructure/MangaPersistenceText.php
> +
Listo @gibmyx

2021-12-23 19:26 UTC, gabrielsalazar8486 commented on src/GJ8486/Manga/Application/MangaCreate.php
>      }
listo @gibmyx

2021-12-23 19:27 UTC, gabrielsalazar8486 commented on src/GJ8486/Manga/Application/MangaUpdate.php
> +        return $this->mangaPresistence->update($manga);
listo @gibmyx

2021-12-23 19:29 UTC, gabrielsalazar8486 commented on src/GJ8486/Manga/Application/MangaUpdate.php
> +        $manga = $this->mangaPresistence->findOne($request['id']);
listo @dmarcanor

2021-12-23 19:29 UTC, gabrielsalazar8486 commented on src/GJ8486/Manga/Infrastructure/MangaPersistenceText.php
>             : [];
listo @gibmyx

2021-12-23 19:29 UTC, gabrielsalazar8486 commented on src/GJ8486/Manga/Application/MangaCreate.php
>      public function __invoke(array $request)
listo @fjmn2001

2021-12-23 19:30 UTC, gabrielsalazar8486 commented on src/GJ8486/Manga/Domain/Manga.php
> +    public function autorChange(string $new_value)
listo @dmarcanor

2021-12-23 19:41 UTC, gabrielsalazar8486 commented on tests/GJ8486/Manga/Application/MangaCreateTest.php
>          $repository = new MangaPersistenceText;
por los momento no toca nada externo, se creo que para este test se avía quedado en una implementar sencilla @dmarcanor

2021-12-24 12:39 UTC, gibmyx approved these changes
Listo @gabrielsalazar8486

2021-12-24 14:17 UTC, dmarcanor approved these changes
Listo @gabrielsalazar8486

2021-12-24 14:17 UTC, merged