Ejercicio 4. Course Testing
fjmn2001/testing-course pull request #19
Opened 2021-12-22 13:48 UTC by gibmyx

2021-12-22 17:22 UTC, fjmn2001 approved these changes
@gibmyx aprobado pero con algunos comentarios en cuestión de nombres de clases y métodos.

2021-12-22 17:22 UTC, fjmn2001 commented on src/Gibmyx/Application/Create/MovieCreate.php
> +final class MovieCreate
@gibmyx el nombre de los casos de uso debe ser en infinitivo, como creator, updater, checker, etc...

2021-12-22 17:22 UTC, fjmn2001 commented on src/Gibmyx/Domain/Entity/Movie.php
> +    public function nameChange($newName): void
@gibmyx cuando es la solicitud para realizar una acción el nombre es AcciónPropiedad, eje changeName

2021-12-23 13:20 UTC, dmarcanor commented on src/Gibmyx/Application/Create/MovieCreateRequest.php
> +final class MovieCreateRequest
En la linea del comentario del señor francisco, esta clase también le tienes que cambiar el nombre

2021-12-23 13:24 UTC, dmarcanor commented on tests/Gibmyx/Application/Create/MovieCreateTest.php
> +        ($create)(new MovieCreateRequest(
Acá podrías usar un objectMother para el MovieCreatorRequest @gibmyx

2021-12-23 13:26 UTC, dmarcanor commented on tests/Gibmyx/Application/Finder/MovieFinderTest.php
> +        $this->assertEquals($movie->id(), $response->id());
Acá el assert lo pordrías hacer del response (MovieResponse) contra un ObjectMother de MovieResponse. ejemplo:

$movie = MovieMother::random();
$response = MovieResponseMother::fromEntity($movie);

2021-12-23 13:26 UTC, dmarcanor approved these changes
@gibmyx  listo. Deje algunos comentarios

2021-12-23 19:04 UTC, gabrielsalazar8486 requested changes

2021-12-23 19:04 UTC, gabrielsalazar8486 commented on src/Gibmyx/Application/Updater/MovieUpdate.php
> +final class MovieUpdate
El nombre de los casos de uso debe ser en infinitivo @gibmyx

2021-12-23 19:04 UTC, gabrielsalazar8486 commented on src/Gibmyx/Application/Updater/MovieUpdateRequest.php
> +final class MovieUpdateRequest
Si se corrige el nombre del caso de uso debería a MovieUpdaterRequest, @gibmyx

2021-12-27 13:42 UTC, gibmyx commented on tests/Gibmyx/Application/Create/MovieCreateTest.php
> +        ($create)(new MovieCreateRequest(
lo estare aplicando en futura actualizaciones, gracias por la recomendacion

2021-12-27 14:20 UTC, gabrielsalazar8486 approved these changes

2021-12-27 14:20 UTC, merged